import type { Province, FeedItem, Reel, Community, SearchSuggestion } from './types';

// ── PROVINCIAS DE ECUADOR (24) con datos simulados realistas ──────────
export const PROVINCES: Province[] = [
  { id: 'guayas', name: 'Guayas', capital: 'Guayaquil', population: 4387434, contracts: 1847, contractValue: 892_000_000, alerts: 47, laws: 12, denuncias: 384, riskLevel: 'alto', activeDebates: 23, coords: { cx: 200, cy: 370 } },
  { id: 'pichincha', name: 'Pichincha', capital: 'Quito', population: 3228233, contracts: 2103, contractValue: 1_240_000_000, alerts: 31, laws: 28, denuncias: 219, riskLevel: 'medio', activeDebates: 41, coords: { cx: 235, cy: 190 } },
  { id: 'manabi', name: 'Manabí', capital: 'Portoviejo', population: 1562079, contracts: 743, contractValue: 310_000_000, alerts: 22, laws: 5, denuncias: 127, riskLevel: 'medio', activeDebates: 14, coords: { cx: 155, cy: 280 } },
  { id: 'azuay', name: 'Azuay', capital: 'Cuenca', population: 881394, contracts: 521, contractValue: 240_000_000, alerts: 9, laws: 7, denuncias: 86, riskLevel: 'bajo', activeDebates: 18, coords: { cx: 260, cy: 430 } },
  { id: 'el-oro', name: 'El Oro', capital: 'Machala', population: 715751, contracts: 412, contractValue: 180_000_000, alerts: 15, laws: 3, denuncias: 91, riskLevel: 'medio', activeDebates: 11, coords: { cx: 210, cy: 470 } },
  { id: 'esmeraldas', name: 'Esmeraldas', capital: 'Esmeraldas', population: 643654, contracts: 298, contractValue: 145_000_000, alerts: 19, laws: 2, denuncias: 103, riskLevel: 'alto', activeDebates: 8, coords: { cx: 185, cy: 120 } },
  { id: 'tungurahua', name: 'Tungurahua', capital: 'Ambato', population: 590600, contracts: 367, contractValue: 160_000_000, alerts: 7, laws: 4, denuncias: 54, riskLevel: 'bajo', activeDebates: 12, coords: { cx: 270, cy: 280 } },
  { id: 'los-rios', name: 'Los Ríos', capital: 'Babahoyo', population: 921763, contracts: 489, contractValue: 210_000_000, alerts: 14, laws: 3, denuncias: 78, riskLevel: 'medio', activeDebates: 9, coords: { cx: 215, cy: 325 } },
  { id: 'chimborazo', name: 'Chimborazo', capital: 'Riobamba', population: 524004, contracts: 312, contractValue: 130_000_000, alerts: 6, laws: 3, denuncias: 41, riskLevel: 'bajo', activeDebates: 7, coords: { cx: 280, cy: 330 } },
  { id: 'loja', name: 'Loja', capital: 'Loja', population: 521154, contracts: 287, contractValue: 125_000_000, alerts: 8, laws: 4, denuncias: 62, riskLevel: 'bajo', activeDebates: 10, coords: { cx: 270, cy: 510 } },
  { id: 'imbabura', name: 'Imbabura', capital: 'Ibarra', population: 476257, contracts: 234, contractValue: 95_000_000, alerts: 5, laws: 2, denuncias: 33, riskLevel: 'bajo', activeDebates: 6, coords: { cx: 240, cy: 140 } },
  { id: 'cotopaxi', name: 'Cotopaxi', capital: 'Latacunga', population: 488716, contracts: 278, contractValue: 110_000_000, alerts: 8, laws: 3, denuncias: 47, riskLevel: 'bajo', activeDebates: 8, coords: { cx: 250, cy: 245 } },
  { id: 'santo-domingo', name: 'Santo Domingo', capital: 'Santo Domingo', population: 458580, contracts: 312, contractValue: 140_000_000, alerts: 11, laws: 2, denuncias: 67, riskLevel: 'medio', activeDebates: 7, coords: { cx: 210, cy: 215 } },
  { id: 'sucumbios', name: 'Sucumbíos', capital: 'Nueva Loja', population: 228052, contracts: 187, contractValue: 85_000_000, alerts: 13, laws: 1, denuncias: 44, riskLevel: 'alto', activeDebates: 5, coords: { cx: 330, cy: 120 } },
  { id: 'orellana', name: 'Orellana', capital: 'El Coca', population: 161338, contracts: 156, contractValue: 72_000_000, alerts: 10, laws: 1, denuncias: 38, riskLevel: 'alto', activeDebates: 4, coords: { cx: 370, cy: 190 } },
  { id: 'santa-elena', name: 'Santa Elena', capital: 'Santa Elena', population: 401178, contracts: 234, contractValue: 98_000_000, alerts: 9, laws: 2, denuncias: 56, riskLevel: 'medio', activeDebates: 6, coords: { cx: 145, cy: 370 } },
  { id: 'bolivar', name: 'Bolívar', capital: 'Guaranda', population: 209993, contracts: 145, contractValue: 55_000_000, alerts: 4, laws: 1, denuncias: 22, riskLevel: 'bajo', activeDebates: 3, coords: { cx: 245, cy: 310 } },
  { id: 'canar', name: 'Cañar', capital: 'Azogues', population: 281396, contracts: 178, contractValue: 68_000_000, alerts: 5, laws: 2, denuncias: 29, riskLevel: 'bajo', activeDebates: 5, coords: { cx: 255, cy: 395 } },
  { id: 'carchi', name: 'Carchi', capital: 'Tulcán', population: 186869, contracts: 121, contractValue: 42_000_000, alerts: 3, laws: 1, denuncias: 18, riskLevel: 'bajo', activeDebates: 3, coords: { cx: 245, cy: 100 } },
  { id: 'morona-santiago', name: 'Morona Santiago', capital: 'Macas', population: 196535, contracts: 167, contractValue: 78_000_000, alerts: 7, laws: 1, denuncias: 31, riskLevel: 'medio', activeDebates: 4, coords: { cx: 340, cy: 400 } },
  { id: 'napo', name: 'Napo', capital: 'Tena', population: 133705, contracts: 123, contractValue: 52_000_000, alerts: 5, laws: 1, denuncias: 21, riskLevel: 'bajo', activeDebates: 3, coords: { cx: 320, cy: 240 } },
  { id: 'pastaza', name: 'Pastaza', capital: 'Puyo', population: 114202, contracts: 98, contractValue: 41_000_000, alerts: 4, laws: 1, denuncias: 17, riskLevel: 'bajo', activeDebates: 2, coords: { cx: 350, cy: 310 } },
  { id: 'zamora-chinchipe', name: 'Zamora Chinchipe', capital: 'Zamora', population: 120416, contracts: 112, contractValue: 48_000_000, alerts: 6, laws: 1, denuncias: 24, riskLevel: 'bajo', activeDebates: 3, coords: { cx: 320, cy: 480 } },
  { id: 'galapagos', name: 'Galápagos', capital: 'Puerto Baquerizo', population: 33042, contracts: 67, contractValue: 28_000_000, alerts: 2, laws: 1, denuncias: 8, riskLevel: 'bajo', activeDebates: 2, coords: { cx: 45, cy: 200 } },
];

// ── FEED ORGÁNICO (30 items realistas) ───────────────────────────
export const ORGANIC_FEED: FeedItem[] = [
  { id: 'f01', type: 'alert', source: 'Contraloría General', sourceCode: 'CGE', sourceColor: '#EF4444', time: 'Hace 3 min', badge: '🔴 ALERTA FISCAL', location: 'El Oro', province: 'el-oro', headline: 'Adjudicación directa de $1.2M sin proceso competitivo en Machala', body: 'El contrato SERCOP-2026-EO-0847 aparece vinculado a 3 empresas inhabilitadas previamente. La Contraloría activó proceso de auditoría especial al GAD Municipal de Machala.', tags: ['#CorrienteOro', '#SERCOPWatch', '#Machala'], impact: 'ALTO', likes: 2847, comments: 384, shares: 1203, aiGenerated: false },
  { id: 'f02', type: 'law', source: 'Asamblea Nacional', sourceCode: 'AN', sourceColor: '#3B82F6', time: 'Hace 22 min', badge: '⚖️ LEGISLATIVO', location: 'Quito', province: 'pichincha', headline: 'Aprobado en primer debate: Art. 14 del Código Tributario — Nuevas tasas a exportaciones agrícolas', body: '98 votos a favor, 22 en contra. La reforma entra en vigencia en 60 días. Afecta directamente a exportadores de banano y camarón de la Costa. Asambleísta Patiño (AP) presentó moción de reconsideración.', tags: ['#LeyTributaria', '#Asamblea', '#Banano'], impact: 'ALTO', likes: 5102, comments: 891, shares: 2340, aiGenerated: false },
  { id: 'f03', type: 'citizen', source: 'María Fernanda V.', sourceCode: 'MF', sourceColor: '#10B981', time: 'Hace 45 min', badge: '📍 DENUNCIA CIUDADANA', location: 'Tarqui, Guayaquil', province: 'guayas', headline: 'Obra aceptada en SERCOP pero calle 29ava sigue destruida — #RoboGuayas', body: 'La plataforma oficial registra la obra como "Recibida con satisfacción" pero en la esquina de la 29ava y Portete hay un hueco de 2 metros. Los vecinos adjuntan video de drones mostrando el estado real.', tags: ['#RoboGuayas', '#ObraPublica', '#Guayaquil'], impact: 'MEDIO', likes: 1847, comments: 523, shares: 876, mediaType: 'video', aiGenerated: false },
  { id: 'f04', type: 'data', source: 'EcuaWatch IA', sourceCode: '🤖', sourceColor: '#8B5CF6', time: 'Hace 1h', badge: '📊 ANÁLISIS AUTOMÁTICO', location: 'Nacional', province: 'pichincha', headline: 'Anomalía detectada: $47M en contratos de salud adjudicados al mismo grupo empresarial en 14 provincias', body: 'El motor de análisis cruzó datos de SERCOP con el catastro del SRI y detectó que 7 empresas con el mismo representante legal acumulan el 34% de los contratos de insumos médicos del IESS en 2025.', tags: ['#IADetecta', '#IESS', '#Transparencia'], impact: 'ALTO', likes: 8934, comments: 1247, shares: 4521, mediaType: 'chart', aiGenerated: true },
  { id: 'f05', type: 'debate', source: 'Comunidad Guayaquil', sourceCode: 'CG', sourceColor: '#F59E0B', time: 'Hace 2h', badge: '💬 DEBATE ABIERTO', location: 'Guayaquil', province: 'guayas', headline: '¿Debe el Municipio de Guayaquil publicar el detalle de los $340M del presupuesto 2026?', body: '1,247 ciudadanos ya votaron: 89% dice SÍ. El GAD de Guayaquil ha publicado solo resúmenes. EcuaWatch propone apertura total. Únete al debate.', tags: ['#PresupuestoAbierto', '#Guayaquil', '#Debate'], impact: 'MEDIO', likes: 3421, comments: 1247, shares: 892, aiGenerated: false },
  { id: 'f06', type: 'alert', source: 'SRI - Servicio Rentas', sourceCode: 'SRI', sourceColor: '#DC2626', time: 'Hace 2h', badge: '🔴 TRIBUTARIO', location: 'Nacional', province: 'pichincha', headline: 'Recaudación de abril cae 12% vs mismo mes 2025 — $287M menos de lo proyectado', body: 'El SRI reporta que la recaudación del IVA interno cayó significativamente. Los analistas señalan la reducción del consumo y la informalidad creciente como factores principales.', tags: ['#SRI', '#Recaudación', '#Economía'], impact: 'ALTO', likes: 4210, comments: 678, shares: 1890, aiGenerated: false },
  { id: 'f07', type: 'citizen', source: 'Carlos Mendoza P.', sourceCode: 'CM', sourceColor: '#06B6D4', time: 'Hace 3h', badge: '📍 INFRAESTRUCTURA', location: 'Portoviejo, Manabí', province: 'manabi', headline: 'Hospital del día de Portoviejo sin agua potable por tercera semana consecutiva', body: 'Los pacientes del área de diálisis deben llevar su propia agua para los tratamientos. El director del hospital dijo que "están gestionando ante SENAGUA". 14 pacientes en riesgo.', tags: ['#SaludPública', '#Manabí', '#Portoviejo'], impact: 'ALTO', likes: 6781, comments: 923, shares: 3402, aiGenerated: false },
  { id: 'f08', type: 'data', source: 'EcuaWatch IA', sourceCode: '🤖', sourceColor: '#8B5CF6', time: 'Hace 4h', badge: '📈 TENDENCIA', location: 'Nacional', province: 'guayas', headline: 'Guayas concentra el 42% de denuncias ciudadanas de abril — 384 reportes activos', body: 'El mapa de calor muestra que el 65% de las denuncias se concentran en el sur de Guayaquil (parroquias Ximena y Tarqui). Las principales categorías: obras inconclusas (38%), seguridad (27%), servicios básicos (21%).', tags: ['#DatosGuayas', '#MapaCalor', '#Denuncias'], impact: 'MEDIO', likes: 2103, comments: 312, shares: 890, mediaType: 'chart', aiGenerated: true },
  { id: 'f09', type: 'law', source: 'Registro Oficial', sourceCode: 'RO', sourceColor: '#1D4ED8', time: 'Hace 5h', badge: '📜 LEY PUBLICADA', location: 'Nacional', province: 'pichincha', headline: 'RO-2026-847: Ley Orgánica de Protección de Datos Personales — Reglamento operativo entra en vigencia', body: 'Tras 18 meses de espera, el reglamento finalmente establece las multas y procedimientos para empresas que incumplan. Las PYMES tienen 6 meses de gracia para adaptarse.', tags: ['#ProtecciónDatos', '#RegistroOficial', '#PYMES'], impact: 'MEDIO', likes: 1567, comments: 234, shares: 678, aiGenerated: false },
  { id: 'f10', type: 'citizen', source: 'Ana Lucía Torres', sourceCode: 'AT', sourceColor: '#EC4899', time: 'Hace 6h', badge: '🚨 SEGURIDAD', location: 'Durán', province: 'guayas', headline: 'Puente de acceso a Durán cerrado 3 horas por extorsión a conductores — sin presencia policial', body: 'Conductores reportan que grupos organizados cobran "peaje informal" en la vía de acceso al puente. Los videos subidos a EcuaWatch muestran que esto ocurre desde las 10pm cada noche.', tags: ['#SeguridadVial', '#Durán', '#Extorsión'], impact: 'ALTO', likes: 9234, comments: 1567, shares: 5678, mediaType: 'video', aiGenerated: false },
];

// ── REELS ORGÁNICOS ─────────────────────────────────────────────
export const ORGANIC_REELS: Reel[] = [
  { id: 'r01', title: '60 segundos: Lo que la Asamblea aprobó hoy', description: 'Resumen automático de las 3 leyes votadas en la sesión 487. Código Tributario, Ley de Aguas, Presupuesto Complementario.', videoUrl: '', thumbnailUrl: '', duration: 58, author: { name: 'EcuaWatch IA', avatar: '🤖', verified: true }, category: 'Legislativo', tags: ['#AsambleaHoy', '#LeyesEcuador'], likes: 12400, comments: 890, shares: 3400, views: 87000, province: 'pichincha', aiGenerated: true, createdAt: '2026-04-23T14:00:00Z' },
  { id: 'r02', title: 'Mapa de calor: Dónde se concentran los contratos de emergencia', description: 'Visualización de los $1.2B en contratos de emergencia de 2025-2026. El 67% se concentra en 3 provincias.', videoUrl: '', thumbnailUrl: '', duration: 45, author: { name: 'EcuaWatch IA', avatar: '🤖', verified: true }, category: 'Datos', tags: ['#ContratosEmergencia', '#MapaCalor'], likes: 8700, comments: 654, shares: 2100, views: 54000, province: 'guayas', aiGenerated: true, createdAt: '2026-04-23T10:00:00Z' },
  { id: 'r03', title: '🚨 Calle 29ava destruida pero SERCOP dice "terminada"', description: 'Ciudadana graba con dron el estado real de la calle vs lo que dice el portal oficial de contratación.', videoUrl: '', thumbnailUrl: '', duration: 32, author: { name: 'María Fernanda V.', avatar: '👤', verified: false }, category: 'Denuncia', tags: ['#RoboGuayas', '#ObraPublica'], likes: 24500, comments: 3200, shares: 12000, views: 189000, province: 'guayas', aiGenerated: false, createdAt: '2026-04-23T08:00:00Z' },
  { id: 'r04', title: 'Entendiendo la nueva Ley de Datos en 90 segundos', description: 'Te explicamos qué cambia con el RO-2026-847 y cómo te afecta como ciudadano y emprendedor.', videoUrl: '', thumbnailUrl: '', duration: 87, author: { name: 'EcuaWatch IA', avatar: '🤖', verified: true }, category: 'Educativo', tags: ['#ProtecciónDatos', '#TusDerechos'], likes: 6300, comments: 412, shares: 1800, views: 43000, province: 'pichincha', aiGenerated: true, createdAt: '2026-04-22T20:00:00Z' },
  { id: 'r05', title: 'Hospital sin agua: 14 pacientes de diálisis en riesgo', description: 'Reportaje ciudadano desde el Hospital del Día de Portoviejo. Tercera semana sin agua potable.', videoUrl: '', thumbnailUrl: '', duration: 67, author: { name: 'Carlos Mendoza', avatar: '👤', verified: false }, category: 'Denuncia', tags: ['#SaludPública', '#Manabí'], likes: 31200, comments: 4500, shares: 18000, views: 245000, province: 'manabi', aiGenerated: false, createdAt: '2026-04-22T16:00:00Z' },
  { id: 'r06', title: '¿Quién financia al asambleísta X? Seguimos el dinero', description: 'Cruce de datos: financistas de campaña vs adjudicatarios de contratos públicos en el mismo período.', videoUrl: '', thumbnailUrl: '', duration: 120, author: { name: 'EcuaWatch IA', avatar: '🤖', verified: true }, category: 'Investigación', tags: ['#SigueDinero', '#Transparencia'], likes: 45000, comments: 6700, shares: 28000, views: 390000, province: 'pichincha', aiGenerated: true, createdAt: '2026-04-22T12:00:00Z' },
];

// ── COMUNIDADES ──────────────────────────────────────────────────
export const COMMUNITIES: Community[] = [
  { id: 'c01', name: 'Guayaquil Vigila', slug: 'guayaquil', description: 'Vigilancia ciudadana del GAD Municipal, SERCOP y obras públicas en Guayaquil y parroquias rurales.', icon: '🏙️', coverColor: '#0EA5E9', members: 14832, postsToday: 47, category: 'ciudad', trending: true, tags: ['guayaquil', 'obras', 'sercop'], recentTopics: ['Presupuesto 2026 del GAD', 'Obra inconclusa en Av. 25 de Julio', 'Licitación del Metrovía fase 3'] },
  { id: 'c02', name: 'Asamblea Watch', slug: 'asamblea', description: 'Seguimiento de todos los proyectos de ley, debates y votaciones de la Asamblea Nacional.', icon: '⚖️', coverColor: '#3B82F6', members: 23410, postsToday: 28, category: 'institucion', trending: true, tags: ['asamblea', 'leyes', 'legislativo'], recentTopics: ['Código Tributario Art. 14', 'Ley de Aguas reforma', 'Proforma presupuestaria 2027'] },
  { id: 'c03', name: 'Contraloría Sin Censura', slug: 'contraloria', description: 'Análisis y discusión de informes de auditoría, exámenes especiales y resoluciones de la CGE.', icon: '🔍', coverColor: '#EF4444', members: 8947, postsToday: 15, category: 'institucion', trending: false, tags: ['contraloria', 'auditoría', 'transparencia'], recentTopics: ['Auditoría GAD El Oro', 'Informe IESS Fondos', 'Examen especial Petroecuador'] },
  { id: 'c04', name: 'Quito Transparente', slug: 'quito', description: 'Fiscalización ciudadana del Municipio de Quito, Metro, y obras de infraestructura de la capital.', icon: '🏔️', coverColor: '#8B5CF6', members: 11203, postsToday: 22, category: 'ciudad', trending: false, tags: ['quito', 'metro', 'municipio'], recentTopics: ['Metro de Quito fase 2', 'Presupuesto participativo', 'BRT extensión'] },
  { id: 'c05', name: 'Datos Abiertos Ecuador', slug: 'datos', description: 'Comunidad de científicos de datos, periodistas y ciudadanos que analizan datos públicos del gobierno.', icon: '📊', coverColor: '#10B981', members: 5621, postsToday: 8, category: 'tema', trending: false, tags: ['datos', 'análisis', 'visualización'], recentTopics: ['Dataset SERCOP 2025', 'API del SRI nueva', 'Cómo usar los datos del INEC'] },
  { id: 'c06', name: 'Seguridad Ciudadana', slug: 'seguridad', description: 'Reportes en tiempo real de situaciones de inseguridad, alertas y coordinación vecinal.', icon: '🚨', coverColor: '#F97316', members: 19876, postsToday: 63, category: 'tema', trending: true, tags: ['seguridad', 'alertas', 'emergencias'], recentTopics: ['Extorsión en Durán', 'Números de emergencia', 'App de alertas vecinales'] },
  { id: 'c07', name: 'Cuenca Activa', slug: 'cuenca', description: 'Comunidad de Azuay: patrimonio, medio ambiente, presupuesto municipal y calidad de vida.', icon: '🌿', coverColor: '#059669', members: 6234, postsToday: 11, category: 'ciudad', trending: false, tags: ['cuenca', 'azuay', 'patrimonio'], recentTopics: ['Tranvía ruta nueva', 'Calidad del aire', 'Mercados municipales'] },
  { id: 'c08', name: 'Economía Ecuador', slug: 'economia', description: 'Análisis del PIB, inflación, empleo, deuda pública y política fiscal. Datos del BCE, INEC y MEF.', icon: '💰', coverColor: '#EAB308', members: 7891, postsToday: 14, category: 'tema', trending: false, tags: ['economía', 'pib', 'inflación', 'empleo'], recentTopics: ['PIB Q1 2026', 'Dolarización 25 años', 'Desempleo juvenil'] },
];

// ── SUGERENCIAS DE BÚSQUEDA ──────────────────────────────────────
export const SEARCH_SUGGESTIONS: SearchSuggestion[] = [
  { type: 'ley', title: 'Código Tributario Art. 14', subtitle: 'Reforma aprobada en primer debate — Asamblea Nacional', icon: '⚖️', url: '/explorar?q=codigo+tributario+art+14' },
  { type: 'contrato', title: 'SERCOP-2026-EO-0847', subtitle: 'Adjudicación directa $1.2M — GAD Machala', icon: '📋', url: '/explorar?q=SERCOP-2026-EO-0847' },
  { type: 'entidad', title: 'GAD Municipal de Guayaquil', subtitle: '1,847 contratos · $892M · 47 alertas activas', icon: '🏛️', url: '/explorar?q=GAD+Guayaquil' },
  { type: 'persona', title: 'Asambleísta Patiño (AP)', subtitle: 'Bloque Alianza País · 12 proyectos de ley presentados', icon: '👤', url: '/explorar?q=asamblea+patino' },
  { type: 'provincia', title: 'Guayas', subtitle: '4.3M hab · 384 denuncias · Riesgo: ALTO', icon: '📍', url: '/explorar?q=guayas' },
  { type: 'tema', title: 'Contratos de emergencia 2025', subtitle: '$1.2B en 847 procesos · 3 provincias concentran el 67%', icon: '🔥', url: '/explorar?q=contratos+emergencia+2025' },
  { type: 'entidad', title: 'IESS — Instituto Ecuatoriano de Seguridad Social', subtitle: '2,103 contratos · 31 alertas · Auditorías pendientes: 7', icon: '🏥', url: '/explorar?q=IESS' },
  { type: 'tema', title: 'Protección de datos personales', subtitle: 'RO-2026-847 · Reglamento vigente desde abril 2026', icon: '🔒', url: '/explorar?q=proteccion+datos' },
];
