"""
Seed Data para MongoDB — Datos orgánicos pre-cargados
═══════════════════════════════════════════════════════
Utilizado por content_generator.py para poblar la BD la primera vez.
"""

FEED_ITEMS = [
    {"type": "alert", "source": "Contraloría General", "sourceCode": "CGE", "sourceColor": "#EF4444", "time": "Hace 3 min", "badge": "🔴 ALERTA FISCAL", "location": "El Oro", "province": "el-oro", "headline": "Adjudicación directa de $1.2M sin proceso competitivo en Machala", "body": "El contrato SERCOP-2026-EO-0847 aparece vinculado a 3 empresas inhabilitadas previamente. La Contraloría activó proceso de auditoría especial al GAD Municipal de Machala.", "tags": ["#CorrienteOro", "#SERCOPWatch", "#Machala"], "impact": "ALTO", "likes": 2847, "comments": 384, "shares": 1203, "aiGenerated": False},
    {"type": "law", "source": "Asamblea Nacional", "sourceCode": "AN", "sourceColor": "#3B82F6", "time": "Hace 22 min", "badge": "⚖️ LEGISLATIVO", "location": "Quito", "province": "pichincha", "headline": "Aprobado en primer debate: Art. 14 del Código Tributario — Nuevas tasas a exportaciones agrícolas", "body": "98 votos a favor, 22 en contra. La reforma entra en vigencia en 60 días. Afecta directamente a exportadores de banano y camarón de la Costa.", "tags": ["#LeyTributaria", "#Asamblea", "#Banano"], "impact": "ALTO", "likes": 5102, "comments": 891, "shares": 2340, "aiGenerated": False},
    {"type": "citizen", "source": "María Fernanda V.", "sourceCode": "MF", "sourceColor": "#10B981", "time": "Hace 45 min", "badge": "📍 DENUNCIA CIUDADANA", "location": "Tarqui, Guayaquil", "province": "guayas", "headline": "Obra aceptada en SERCOP pero calle 29ava sigue destruida", "body": "La plataforma oficial registra la obra como 'Recibida con satisfacción' pero en la esquina de la 29ava y Portete hay un hueco de 2 metros.", "tags": ["#RoboGuayas", "#ObraPublica", "#Guayaquil"], "impact": "MEDIO", "likes": 1847, "comments": 523, "shares": 876, "mediaType": "video", "aiGenerated": False},
    {"type": "data", "source": "EcuaWatch IA", "sourceCode": "🤖", "sourceColor": "#8B5CF6", "time": "Hace 1h", "badge": "📊 ANÁLISIS AUTOMÁTICO", "location": "Nacional", "province": "pichincha", "headline": "Anomalía detectada: $47M en contratos de salud adjudicados al mismo grupo empresarial", "body": "El motor de análisis cruzó datos de SERCOP con el catastro del SRI y detectó que 7 empresas con el mismo representante legal acumulan el 34% de los contratos de insumos médicos del IESS.", "tags": ["#IADetecta", "#IESS", "#Transparencia"], "impact": "ALTO", "likes": 8934, "comments": 1247, "shares": 4521, "mediaType": "chart", "aiGenerated": True},
    {"type": "debate", "source": "Comunidad Guayaquil", "sourceCode": "CG", "sourceColor": "#F59E0B", "time": "Hace 2h", "badge": "💬 DEBATE ABIERTO", "location": "Guayaquil", "province": "guayas", "headline": "¿Debe el Municipio de Guayaquil publicar el detalle de los $340M del presupuesto 2026?", "body": "1,247 ciudadanos ya votaron: 89% dice SÍ. EcuaWatch propone apertura total. Únete al debate.", "tags": ["#PresupuestoAbierto", "#Guayaquil", "#Debate"], "impact": "MEDIO", "likes": 3421, "comments": 1247, "shares": 892, "aiGenerated": False},
    {"type": "alert", "source": "SRI - Servicio Rentas", "sourceCode": "SRI", "sourceColor": "#DC2626", "time": "Hace 2h", "badge": "🔴 TRIBUTARIO", "location": "Nacional", "province": "pichincha", "headline": "Recaudación de abril cae 12% vs mismo mes 2025 — $287M menos", "body": "El SRI reporta que la recaudación del IVA interno cayó significativamente. Los analistas señalan la reducción del consumo y la informalidad creciente.", "tags": ["#SRI", "#Recaudación", "#Economía"], "impact": "ALTO", "likes": 4210, "comments": 678, "shares": 1890, "aiGenerated": False},
    {"type": "citizen", "source": "Carlos Mendoza P.", "sourceCode": "CM", "sourceColor": "#06B6D4", "time": "Hace 3h", "badge": "📍 INFRAESTRUCTURA", "location": "Portoviejo, Manabí", "province": "manabi", "headline": "Hospital del día de Portoviejo sin agua potable por tercera semana", "body": "Los pacientes del área de diálisis deben llevar su propia agua. El director dice que 'están gestionando ante SENAGUA'. 14 pacientes en riesgo.", "tags": ["#SaludPública", "#Manabí", "#Portoviejo"], "impact": "ALTO", "likes": 6781, "comments": 923, "shares": 3402, "aiGenerated": False},
    {"type": "data", "source": "EcuaWatch IA", "sourceCode": "🤖", "sourceColor": "#8B5CF6", "time": "Hace 4h", "badge": "📈 TENDENCIA", "location": "Nacional", "province": "guayas", "headline": "Guayas concentra el 42% de denuncias ciudadanas de abril — 384 reportes", "body": "El mapa de calor muestra que el 65% de las denuncias se concentran en el sur de Guayaquil. Principales categorías: obras inconclusas (38%), seguridad (27%).", "tags": ["#DatosGuayas", "#MapaCalor", "#Denuncias"], "impact": "MEDIO", "likes": 2103, "comments": 312, "shares": 890, "mediaType": "chart", "aiGenerated": True},
    {"type": "law", "source": "Registro Oficial", "sourceCode": "RO", "sourceColor": "#1D4ED8", "time": "Hace 5h", "badge": "📜 LEY PUBLICADA", "location": "Nacional", "province": "pichincha", "headline": "RO-2026-847: Ley de Protección de Datos — Reglamento operativo vigente", "body": "Tras 18 meses de espera, el reglamento establece multas y procedimientos. Las PYMES tienen 6 meses de gracia.", "tags": ["#ProtecciónDatos", "#RegistroOficial", "#PYMES"], "impact": "MEDIO", "likes": 1567, "comments": 234, "shares": 678, "aiGenerated": False},
    {"type": "citizen", "source": "Ana Lucía Torres", "sourceCode": "AT", "sourceColor": "#EC4899", "time": "Hace 6h", "badge": "🚨 SEGURIDAD", "location": "Durán", "province": "guayas", "headline": "Puente de acceso a Durán cerrado 3 horas por extorsión — sin policía", "body": "Conductores reportan que grupos organizados cobran 'peaje informal' en la vía de acceso. Videos subidos cada noche desde las 10pm.", "tags": ["#SeguridadVial", "#Durán", "#Extorsión"], "impact": "ALTO", "likes": 9234, "comments": 1567, "shares": 5678, "mediaType": "video", "aiGenerated": False},
]

REELS = [
    {"title": "60 segundos: Lo que la Asamblea aprobó hoy", "description": "Resumen automático de las 3 leyes votadas en la sesión 487.", "videoUrl": "", "thumbnailUrl": "", "duration": 58, "author": {"name": "EcuaWatch IA", "avatar": "🤖", "verified": True}, "category": "Legislativo", "tags": ["#AsambleaHoy", "#LeyesEcuador"], "likes": 12400, "comments": 890, "shares": 3400, "views": 87000, "province": "pichincha", "aiGenerated": True},
    {"title": "Mapa de calor: Contratos de emergencia", "description": "Visualización de $1.2B en contratos de emergencia 2025-2026.", "videoUrl": "", "thumbnailUrl": "", "duration": 45, "author": {"name": "EcuaWatch IA", "avatar": "🤖", "verified": True}, "category": "Datos", "tags": ["#ContratosEmergencia", "#MapaCalor"], "likes": 8700, "comments": 654, "shares": 2100, "views": 54000, "province": "guayas", "aiGenerated": True},
    {"title": "🚨 Calle destruida pero SERCOP dice 'terminada'", "description": "Ciudadana graba con dron el estado real vs portal oficial.", "videoUrl": "", "thumbnailUrl": "", "duration": 32, "author": {"name": "María Fernanda V.", "avatar": "👤", "verified": False}, "category": "Denuncia", "tags": ["#RoboGuayas", "#ObraPublica"], "likes": 24500, "comments": 3200, "shares": 12000, "views": 189000, "province": "guayas", "aiGenerated": False},
    {"title": "Ley de Datos en 90 segundos", "description": "Qué cambia con el RO-2026-847 para ciudadanos y empresas.", "videoUrl": "", "thumbnailUrl": "", "duration": 87, "author": {"name": "EcuaWatch IA", "avatar": "🤖", "verified": True}, "category": "Educativo", "tags": ["#ProtecciónDatos", "#TusDerechos"], "likes": 6300, "comments": 412, "shares": 1800, "views": 43000, "province": "pichincha", "aiGenerated": True},
    {"title": "Hospital sin agua: 14 pacientes en riesgo", "description": "Reportaje ciudadano desde el Hospital del Día de Portoviejo.", "videoUrl": "", "thumbnailUrl": "", "duration": 67, "author": {"name": "Carlos Mendoza", "avatar": "👤", "verified": False}, "category": "Denuncia", "tags": ["#SaludPública", "#Manabí"], "likes": 31200, "comments": 4500, "shares": 18000, "views": 245000, "province": "manabi", "aiGenerated": False},
    {"title": "¿Quién financia al asambleísta X?", "description": "Cruce de datos: financistas de campaña vs adjudicatarios.", "videoUrl": "", "thumbnailUrl": "", "duration": 120, "author": {"name": "EcuaWatch IA", "avatar": "🤖", "verified": True}, "category": "Investigación", "tags": ["#SigueDinero", "#Transparencia"], "likes": 45000, "comments": 6700, "shares": 28000, "views": 390000, "province": "pichincha", "aiGenerated": True},
]

COMMUNITIES = [
    {"id": "c01", "name": "Guayaquil Vigila", "slug": "guayaquil", "description": "Vigilancia ciudadana del GAD Municipal, SERCOP y obras públicas.", "icon": "🏙️", "coverColor": "#0EA5E9", "members": 14832, "postsToday": 47, "category": "ciudad", "trending": True, "tags": ["guayaquil", "obras", "sercop"], "recentTopics": ["Presupuesto 2026 del GAD", "Obra inconclusa Av. 25 de Julio", "Licitación Metrovía fase 3"]},
    {"id": "c02", "name": "Asamblea Watch", "slug": "asamblea", "description": "Seguimiento de proyectos de ley, debates y votaciones.", "icon": "⚖️", "coverColor": "#3B82F6", "members": 23410, "postsToday": 28, "category": "institucion", "trending": True, "tags": ["asamblea", "leyes", "legislativo"], "recentTopics": ["Código Tributario Art. 14", "Ley de Aguas reforma", "Proforma 2027"]},
    {"id": "c03", "name": "Contraloría Sin Censura", "slug": "contraloria", "description": "Análisis de informes de auditoría y resoluciones de la CGE.", "icon": "🔍", "coverColor": "#EF4444", "members": 8947, "postsToday": 15, "category": "institucion", "trending": False, "tags": ["contraloria", "auditoría", "transparencia"], "recentTopics": ["Auditoría GAD El Oro", "Informe IESS Fondos", "Examen especial Petroecuador"]},
    {"id": "c04", "name": "Quito Transparente", "slug": "quito", "description": "Fiscalización del Municipio de Quito, Metro, e infraestructura.", "icon": "🏔️", "coverColor": "#8B5CF6", "members": 11203, "postsToday": 22, "category": "ciudad", "trending": False, "tags": ["quito", "metro", "municipio"], "recentTopics": ["Metro fase 2", "Presupuesto participativo", "BRT extensión"]},
    {"id": "c05", "name": "Datos Abiertos Ecuador", "slug": "datos", "description": "Científicos de datos, periodistas y ciudadanos analizando datos públicos.", "icon": "📊", "coverColor": "#10B981", "members": 5621, "postsToday": 8, "category": "tema", "trending": False, "tags": ["datos", "análisis", "visualización"], "recentTopics": ["Dataset SERCOP 2025", "API del SRI nueva", "Cómo usar datos del INEC"]},
    {"id": "c06", "name": "Seguridad Ciudadana", "slug": "seguridad", "description": "Reportes de inseguridad, alertas y coordinación vecinal.", "icon": "🚨", "coverColor": "#F97316", "members": 19876, "postsToday": 63, "category": "tema", "trending": True, "tags": ["seguridad", "alertas", "emergencias"], "recentTopics": ["Extorsión en Durán", "Números de emergencia", "App alertas vecinales"]},
    {"id": "c07", "name": "Cuenca Activa", "slug": "cuenca", "description": "Comunidad de Azuay: patrimonio, medio ambiente y calidad de vida.", "icon": "🌿", "coverColor": "#059669", "members": 6234, "postsToday": 11, "category": "ciudad", "trending": False, "tags": ["cuenca", "azuay", "patrimonio"], "recentTopics": ["Tranvía ruta nueva", "Calidad del aire", "Mercados municipales"]},
    {"id": "c08", "name": "Economía Ecuador", "slug": "economia", "description": "Análisis del PIB, inflación, empleo, deuda pública y política fiscal.", "icon": "💰", "coverColor": "#EAB308", "members": 7891, "postsToday": 14, "category": "tema", "trending": False, "tags": ["economía", "pib", "inflación", "empleo"], "recentTopics": ["PIB Q1 2026", "Dolarización 25 años", "Desempleo juvenil"]},
]
